### ISSUE TITLE
Style switcher 

### ISSUE THREAD

**Issue by moatazalaa14** [IEEE-AlAzhar/Official-Website#29]
I think we make a style switcher instead of (dark & light mode) 
![styleSwitcher](https://user-images.githubusercontent.com/52619217/81519844-cd513f80-9342-11ea-8b9c-106b329176a6.PNG)

**Comment by IEEE-AlAzhar** [comment]
We added `dark mode` to make the whole process as simple as possible and no need for style switcher as it doesn't help user on anything.
