### ISSUE TITLE
About Page - Team structure image[Severe]

### ISSUE THREAD

**Issue by AbudZohair** [IEEE-AlAzhar/Official-Website#44]
**Structure image logic should be Refactored** 

-  the 2500px image is renderd on 800px screen width.

- horizontal scroll bar

**Comment by dvmhmdsd** [comment]
Please provide a screenshot for illustration as I didn't see the proplem

**Comment by AbudZohair** [comment]
> Please provide a screenshot for illustration as I didn't see the proplem

there were 3 images for different screen sizes with the logic provided if the screen width between (767: 1200) px

the 2500px image is rendered
