### ISSUE TITLE
Blogs Page (createdAt Date Logic) [Severe]

### ISSUE THREAD

**Issue by AbudZohair** [IEEE-AlAzhar/Official-Website#45]
- createdAt Date Logic Should be refactored to be supported on firefox 
- Replace GMTString to UTCString
![Blog date issue](https://user-images.githubusercontent.com/22384077/81664938-5ac68980-9440-11ea-8931-197bc3ec94b2.PNG)

**Comment by dvmhmdsd** [comment]
What is the proplem of the date logic in firefox ? I tried it and no proplems.

**Comment by AbudZohair** [comment]
> What is the proplem of the date logic in firefox ? I tried it and no proplems.

the Previous date formats weren't supported via firefox and support the "/" instead of "-"
but with the new format, everything is working good
