### ISSUE TITLE
Try to make naming of commits more descriptive 

### ISSUE THREAD

**Issue by MahmoudMabrok** [IEEE-AlAzhar/Official-Website#54]
For examples 
![Screen Shot 2020-06-06 at 3 35 38 PM](https://user-images.githubusercontent.com/13488900/83945534-8e13f280-a80b-11ea-8774-ec95457a665d.png)

Here I do not know what **edits** were done. 
Naming is helpful for both developers (also contributors), recruiter (when he sees naming this indicates some points for him).

At end Thanks for this awesome project, hope u keep moving.

**Comment by dvmhmdsd** [comment]
Thanks Mahmoud for your feedback, we'll take care of this next commit isA.
